# list an arbitrary set of topics to  subscribe to and stream:

stream_time: 60  # seconds

topics: [["/odom",                          ],
         ["/absodom",                       ],
         ["/stereo/right/camera_info",      ],
         ["/stereo/right/image_raw",        ],
         ["/blueview_driver/ranges",        ],
         ["/blueview_driver/image_color",   ], 
         ["/ooka",                          ]]

