# list an arbitrary set of topics to  subscribe to and stream:
# over write default stream time on specific topics in this config
# 

stream_time: 60  # seconds

# potential parameters

# determines how frequently unavailable topics are resubscribed to:
# resubscriber_period : 5.0 # seconds

# adds additional topics to stream, also overrides default stream time
# topics : [["/odom", 20], ["/absodom", 20]]

# sets bag package path, default to home/user/bags/current-date
# bag_package_path : "home/sub8/bags"
